version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9080:9080"
    networks:
      - main-network



networks:
  main-network:
    driver: bridge